#include "data.h"

const RuleInstructionType M = RuleInstructionType::Meta;
const RuleInstructionType U = RuleInstructionType::Unused;


static std::map<std::string, std::vector<std::string>> metaRules = {
	{"a", {"a", "ā", "i", "ī", "u", "ū", "e", "ē", "ie", "ai",
			"ei", "au", "ou", "oi", "ui", "o", "eu", "iu"}},
	{"b", {"g", "ģ", "d", "dz", "dž", "b", "z", "ž"}},
	{"c", {"k", "ķ", "t", "c", "č", "p", "s", "š"}},
	{"d", {"b", "c", "č", "d", "dz", "dž", "f", "g", "ģ", "h",
			"j", "k", "ķ", "l", "ļ", "m", "n", "ņ", "p", "r",
			"s", "š", "t", "v", "z", "ž"}},
	{"e", {"ie", "ei", "e", "ē", "i", "ī", "č", "dž", "f", "ģ",
			"h", "j", "ķ", "ļ", "ņ", "š", "ž"}},
	{"f", {"dž", "ij", "ģēt", "ģētik", "ģētisk", "h", "hij", "īd", "īn", "j",
			"kcij", "kij", "ks", "ld", "nc", "nd", "nis", "nīt", "ntisk", "nt",
			"pej", "pejisk", "ps", "psij", "rd", "rdz", "rej", "rf", "rg", "rk",
			"rnij", "rs", "rt", "rtij", "sk", "stik", "stisk", "tist", "tl", "v",
			"vij", "vism", "vistisk", "vist", "zerist", "zer"}},
	{"g", {"bij", "bik", "bisk", "bism", "cij", "dej", "dij", "dik", "diķ", "disk",
			"f", "felisk", "fij", "fik", "fisk", "fism", "fistisk", "gien", "gist", "ģik",
			"ģij", "ģisk", "gism", "liķ", "mik", "mist", "mistik", "mistisk", "nij", "nik",
			"niķ", "nisk", "nist", "nistik", "nistisk", "peisk", "piet", "pij", "rik", "risk",
			"rism", "ristisk", "tiķ"}},
	{"h", {"iem", "am", "us", "os", "s", "a", "u", "ā", "i"}},
	{"i", {"skr", "skl", "skv", "spl", "spļ", "spr", "str", "štr", "spr", "bj",
			"bl", "bļ", "br", "dņ", "dr", "dv", "dz", "dž", "gl", "gļ",
			"gn", "gr", "gv", "kl", "kļ", "kn", "kņ", "kr", "kv", "pl",
			"pļ", "pn", "pr", "tr", "tv", "sl", "sm", "sn", "sv", "šļ",
			"šm", "šn", "šņ", "šv", "zl", "zn", "zv", "žļ", "žm", "žņ",
			"žv", "sk", "sc", "sp", "st", "šķ", "šp", "št", "b", "c",
			"č", "d", "f", "g", "ģ", "h", "j", "k", "ķ", "l",
			"ļ", "m", "n", "ņ", "p", "r", "s", "š", "t", "v",
			"z", "ž"}},
	{"j", {"a", "ā", "au", "ai", "u", "ū", "o"}},
	{"k", {"b", "c", "d", "g", "k", "l", "m", "n", "p", "r",
			"s", "t", "v", "z"}},
	{"l", {"e", "a", "i", "u"}},
	{"m", {"jama", "jamu", "jamai", "jamo", "jamā", "jams", "jamam", "jamajam", "jums", "juma",
			"jumi", "jumos", "jumiem"}},
	{"n", {"pa", "par", "pār", "at", "ap", "sa", "ne", "no", "iz", "uz",
			"aiz"}},
	{"o", {"ām", "ās", "as", "ai", "a", "u", "ā"}},
	{"p", {"ēm", "ēs", "es", "ei", "e", "i", "ē", "u"}},
	{"r", {"iem", "im", "us", "is", "os", "i", "ī", "a", "u"}},
	{"s", {"ie", "ī", "ē", "ū", "ā"}},
	{"v", {"au", "ai", "ā", "ē", "ī", "ie", "ei"}},
};


static std::vector<Rule> rules = {
	{/* left */                    "M:*", /* text */            "ō", /* right */                    "M:*", /* -> */ "oo"},
	{/* left */                    "M:*", /* text */            "-", /* right */                    "M:*", /* -> */ "-"},
	{/* left */                    "M:*", /* text */            "'", /* right */                    "M:*", /* -> */ "'"},
	{/* left */                    "M:#", /* text */          "110", /* right */                    "M:#", /* -> */ "s_i_m_t_d_e_s_m_i_t"},
	{/* left */                    "M:#", /* text */           "10", /* right */                    "M:#", /* -> */ "d_e_s_m_i_t"},
	{/* left */                    "M:#", /* text */           "11", /* right */                    "M:#", /* -> */ "v_ie_n_p_a_ts_m_i_t"},
	{/* left */                    "M:#", /* text */           "12", /* right */                    "M:#", /* -> */ "d_iu_p_a_ts_m_i_t"},
	{/* left */                    "M:#", /* text */           "13", /* right */                    "M:#", /* -> */ "t_r_ii_s_p_a_ts_m_i_t"},
	{/* left */                    "M:#", /* text */           "14", /* right */                    "M:#", /* -> */ "tS_e_t_r_p_a_ts_m_i_t"},
	{/* left */                    "M:#", /* text */           "15", /* right */                    "M:#", /* -> */ "p_ie_ts_p_a_ts_m_i_t"},
	{/* left */                    "M:#", /* text */           "16", /* right */                    "M:#", /* -> */ "s_e_S_p_a_ts_m_i_t"},
	{/* left */                    "M:#", /* text */           "17", /* right */                    "M:#", /* -> */ "s_e_p_t_i_J_p_a_ts_m_i_t"},
	{/* left */                    "M:#", /* text */           "18", /* right */                    "M:#", /* -> */ "a_s_t_uo_J_p_a_ts_m_i_t"},
	{/* left */                    "M:#", /* text */           "19", /* right */                    "M:#", /* -> */ "d_e_v_i_J_p_a_ts_m_i_t"},
	{/* left */                    "M:#", /* text */           "20", /* right */                    "M:#", /* -> */ "d_iu_d_e_s_m_i_t"},
	{/* left */                    "M:#", /* text */           "30", /* right */                    "M:#", /* -> */ "t_r_ii_s_d_e_s_m_i_t"},
	{/* left */                    "M:#", /* text */           "40", /* right */                    "M:#", /* -> */ "tS_e_t_r_d_e_s_m_i_t"},
	{/* left */                    "M:#", /* text */           "50", /* right */                    "M:#", /* -> */ "p_ie_ts_d_e_s_m_i_t"},
	{/* left */                    "M:#", /* text */           "60", /* right */                    "M:#", /* -> */ "s_e_S_d_e_s_m_i_t"},
	{/* left */                    "M:#", /* text */           "70", /* right */                    "M:#", /* -> */ "s_e_p_t_i_J_d_e_s_m_i_t"},
	{/* left */                    "M:#", /* text */           "80", /* right */                    "M:#", /* -> */ "a_s_t_uo_J_d_e_s_m_i_t"},
	{/* left */                    "M:#", /* text */           "90", /* right */                    "M:#", /* -> */ "d_e_v_i_J_d_e_s_m_i_t"},
	{/* left */                    "M:#", /* text */          "100", /* right */                    "M:#", /* -> */ "s_i_m_t"},
	{/* left */                    "M:#", /* text */         "1000", /* right */                    "M:#", /* -> */ "t_uu_k_s_t_uo_S"},
	{/* left */                       "", /* text */            "0", /* right */                       "", /* -> */ "n_u_ll_ex"},
	{/* left */                       "", /* text */            "1", /* right */                       "", /* -> */ "v_ie_n_s"},
	{/* left */                       "", /* text */            "2", /* right */                       "", /* -> */ "d_i_v_ix"},
	{/* left */                       "", /* text */            "3", /* right */                       "", /* -> */ "t_r_ii_s"},
	{/* left */                       "", /* text */            "4", /* right */                       "", /* -> */ "tS_e_t_r_ix"},
	{/* left */                       "", /* text */            "5", /* right */                       "", /* -> */ "p_ie_ts_ix"},
	{/* left */                       "", /* text */            "6", /* right */                       "", /* -> */ "s_e_SS_ix"},
	{/* left */                       "", /* text */            "7", /* right */                       "", /* -> */ "s_e_p_t_i_J_ix"},
	{/* left */                       "", /* text */            "8", /* right */                       "", /* -> */ "a_s_t_uo_J_ix"},
	{/* left */                       "", /* text */            "9", /* right */                       "", /* -> */ "d_e_v_i_J_ix"},
	{/* left */                    "M:#", /* text */        "aģent", /* right */                    "M:^", /* -> */ "a_G_e_n_t"},
	{/* left */                    "M:#", /* text */          "cer", /* right */                    "M:#", /* -> */ "ts_E_r"},
	{/* left */                    "M:#", /* text */         "esot", /* right */                    "M:#", /* -> */ "E_s_uo_t"},
	{/* left */                    "M:#", /* text */         "foto", /* right */                    "M:#", /* -> */ "f_o_t_oo"},
	{/* left */                    "M:#", /* text */         "foto", /* right */                    "M:^", /* -> */ "f_o_t_oo"},
	{/* left */                    "M:#", /* text */           "ja", /* right */                    "M:#", /* -> */ "j_a"},
	{/* left */                    "M:#", /* text */           "ka", /* right */                    "M:#", /* -> */ "k_a"},
	{/* left */                    "M:#", /* text */          "kas", /* right */                    "M:#", /* -> */ "k_a_s"},
	{/* left */                    "M:#", /* text */       "mākoņi", /* right */                    "M:#", /* -> */ "m_aa_k_uo_J_ix"},
	{/* left */                    "M:#", /* text */           "no", /* right */                    "M:#", /* -> */ "n_uo"},
	{/* left */                    "M:#", /* text */           "no", /* right */                    "M:^", /* -> */ "n_uo"},
	{/* left */                    "M:#", /* text */           "pa", /* right */                    "M:#", /* -> */ "p_a"},
	{/* left */                    "M:#", /* text */          "šis", /* right */                    "M:#", /* -> */ "S_i_s"},
	{/* left */                    "M:#", /* text */        "šogad", /* right */                    "M:#", /* -> */ "S_uo_g_a_d"},
	{/* left */                    "M:#", /* text */          "tas", /* right */                    "M:#", /* -> */ "t_a_s"},
	{/* left */                    "M:#", /* text */        "astoņ", /* right */                    "M:*", /* -> */ "a_s_t_uo_J"},
	{/* left */                    "M:#", /* text */        "tomēr", /* right */                    "M:#", /* -> */ "t_uo_m_EE_r"},
	{/* left */                    "M:#", /* text */        "vēlāk", /* right */                    "M:#", /* -> */ "v_EE_l_aa_k"},
	{/* left */                    "M:#", /* text */     "svētdien", /* right */                    "M:*", /* -> */ "s_v_ee_d_ie_n"},
	{/* left */                    "M:#", /* text */     "sestdien", /* right */                    "M:*", /* -> */ "s_e_z_d_ie_n"},
	{/* left */                    "M:#", /* text */    "piektdien", /* right */                    "M:*", /* -> */ "p_ie_g_d_ie_n"},
	{/* left */                    "M:#", /* text */   "ceturtdien", /* right */                    "M:*", /* -> */ "ts_E_t\\_u_r_d_ie_n"},
	{/* left */                    "M:#", /* text */          "otr", /* right */                    "M:*", /* -> */ "uo_t_r"},
	{/* left */                    "M:*", /* text */          "dom", /* right */                    "M:*", /* -> */ "d_uo_m"},
	{/* left */                    "M:*", /* text */          "dom", /* right */                    "M:*", /* -> */ "d_uo_m"},
	{/* left */                "M:# M:n", /* text */        "dzejo", /* right */                    "M:*", /* -> */ "dz_e_j_uo"},
	{/* left */                    "M:#", /* text */        "dzejo", /* right */                    "M:*", /* -> */ "dz_e_j_uo"},
	{/* left */                    "M:^", /* text */            "o", /* right */                    "M:m", /* -> */ "uo"},
	{/* left */                    "M:#", /* text */           "ae", /* right */                    "M:^", /* -> */ "ai"},
	{/* left */                    "M:d", /* text */           "aj", /* right */                    "M:d", /* -> */ "ai"},
	{/* left */                    "M:d", /* text */           "ai", /* right */                    "M:d", /* -> */ "ai"},
	{/* left */                    "M:^", /* text */           "ai", /* right */                    "M:#", /* -> */ "ai"},
	{/* left */                    "M:^", /* text */           "aj", /* right */                    "M:#", /* -> */ "ai"},
	{/* left */                    "M:*", /* text */           "ai", /* right */                    "M:*", /* -> */ "ai"},
	{/* left */                    "M:d", /* text */           "av", /* right */                    "M:d", /* -> */ "au"},
	{/* left */                    "M:^", /* text */           "av", /* right */                    "M:#", /* -> */ "au"},
	{/* left */                    "M:*", /* text */           "au", /* right */                    "M:*", /* -> */ "au"},
	{/* left */                    "M:d", /* text */           "āj", /* right */                    "M:a", /* -> */ "aa_j"},
	{/* left */                    "M:*", /* text */            "ā", /* right */                    "M:*", /* -> */ "aa"},
	{/* left */                    "M:d", /* text */            "a", /* right */                    "M:#", /* -> */ "ax"},
	{/* left */                    "M:^", /* text */            "a", /* right */                "U:s M:#", /* -> */ "ax"},
	{/* left */                    "M:*", /* text */            "a", /* right */                    "M:*", /* -> */ "a"},
	{/* left */                    "M:^", /* text */            "b", /* right */                    "M:c", /* -> */ "p"},
	{/* left */                    "M:*", /* text */            "b", /* right */                    "M:*", /* -> */ "b"},
	{/* left */                    "M:^", /* text */            "c", /* right */                    "M:b", /* -> */ "dz"},
	{/* left */            "M:# M:d M:l", /* text */            "c", /* right */                    "M:l", /* -> */ "ts"},
	{/* left */                    "M:*", /* text */            "c", /* right */                    "M:*", /* -> */ "ts"},
	{/* left */                    "M:^", /* text */            "č", /* right */                    "M:b", /* -> */ "dZ"},
	{/* left */                    "M:*", /* text */            "č", /* right */                    "M:*", /* -> */ "tS"},
	{/* left */                    "M:^", /* text */           "dz", /* right */                    "M:c", /* -> */ "ts"},
	{/* left */                    "M:*", /* text */           "dz", /* right */                    "M:*", /* -> */ "dz"},
	{/* left */                    "M:^", /* text */          "džs", /* right */                    "M:#", /* -> */ "tS"},
	{/* left */                    "M:^", /* text */           "dž", /* right */                    "M:c", /* -> */ "tS"},
	{/* left */                    "M:*", /* text */           "dž", /* right */                    "M:*", /* -> */ "dZ"},
	{/* left */                    "M:^", /* text */           "ds", /* right */            "U:m U:i U:t", /* -> */ "ts"},
	{/* left */                    "M:^", /* text */           "ds", /* right */                    "M:#", /* -> */ "ts"},
	{/* left */                    "M:^", /* text */            "d", /* right */                    "M:c", /* -> */ "t"},
	{/* left */                    "M:*", /* text */            "d", /* right */                    "M:*", /* -> */ "d"},
	{/* left */                    "M:d", /* text */            "e", /* right */                    "M:#", /* -> */ "ex"},
	{/* left */                    "M:d", /* text */            "e", /* right */                "U:s M:#", /* -> */ "ex"},
	{/* left */                    "M:^", /* text */            "ē", /* right */                    "M:#", /* -> */ "ee"},
	{/* left */                    "M:d", /* text */           "ej", /* right */                    "M:d", /* -> */ "ei"},
	{/* left */                "M:# U:n", /* text */           "ei", /* right */                    "M:^", /* -> */ "e_i"},
	{/* left */                    "M:^", /* text */           "ej", /* right */                    "M:#", /* -> */ "ei"},
	{/* left */                    "M:*", /* text */           "ei", /* right */                    "M:*", /* -> */ "ei"},
	{/* left */                    "M:d", /* text */           "ev", /* right */                    "M:d", /* -> */ "eu"},
	{/* left */                    "M:^", /* text */           "ev", /* right */                    "M:#", /* -> */ "eu"},
	{/* left */                "M:# U:n", /* text */            "e", /* right */                    "M:^", /* -> */ "e"},
	{/* left */                "M:# U:č", /* text */            "e", /* right */            "U:t U:r M:^", /* -> */ "e"},
	{/* left */                    "M:^", /* text */            "e", /* right */                "M:k M:j", /* -> */ "E"},
	{/* left */                    "M:^", /* text */            "e", /* right */            "M:k M:k M:j", /* -> */ "E"},
	{/* left */                    "M:^", /* text */            "e", /* right */            "M:* U:f M:*", /* -> */ "e"},
	{/* left */            "M:* U:f M:*", /* text */            "e", /* right */                    "M:^", /* -> */ "e"},
	{/* left */                    "M:*", /* text */            "e", /* right */                    "M:*", /* -> */ "E"},
	{/* left */                    "M:^", /* text */            "ē", /* right */            "U:n M:h M:#", /* -> */ "EE"},
	{/* left */                    "M:^", /* text */            "ē", /* right */            "U:k M:h M:#", /* -> */ "EE"},
	{/* left */                    "M:^", /* text */            "ē", /* right */            "U:k M:o M:#", /* -> */ "EE"},
	{/* left */                    "M:^", /* text */            "ē", /* right */                "M:k M:j", /* -> */ "EE"},
	{/* left */                    "M:^", /* text */            "ē", /* right */            "M:k M:k M:j", /* -> */ "EE"},
	{/* left */                    "M:^", /* text */            "e", /* right */                    "M:e", /* -> */ "e"},
	{/* left */                    "M:*", /* text */            "ē", /* right */               "U:ts M:#", /* -> */ "EE"},
	{/* left */                    "M:^", /* text */            "ē", /* right */                    "M:e", /* -> */ "ee"},
	{/* left */            "M:* U:f M:*", /* text */            "ē", /* right */                    "M:^", /* -> */ "ee"},
	{/* left */                    "M:^", /* text */            "ē", /* right */            "M:* U:f M:*", /* -> */ "ee"},
	{/* left */                    "M:*", /* text */            "ē", /* right */                    "M:*", /* -> */ "EE"},
	{/* left */                    "M:*", /* text */            "f", /* right */                    "M:*", /* -> */ "f"},
	{/* left */                    "M:^", /* text */            "g", /* right */                    "M:c", /* -> */ "k"},
	{/* left */                    "M:*", /* text */            "g", /* right */                    "M:*", /* -> */ "g"},
	{/* left */                    "M:^", /* text */            "ģ", /* right */                    "M:c", /* -> */ "K"},
	{/* left */                    "M:*", /* text */            "ģ", /* right */                    "M:*", /* -> */ "G"},
	{/* left */                    "M:*", /* text */            "h", /* right */                    "M:*", /* -> */ "x"},
	{/* left */                    "M:*", /* text */           "ie", /* right */                    "M:*", /* -> */ "ie"},
	{/* left */                    "M:d", /* text */            "i", /* right */                    "M:#", /* -> */ "ix"},
	{/* left */                    "M:d", /* text */            "i", /* right */                "U:s M:#", /* -> */ "ix"},
	{/* left */                    "M:d", /* text */           "iv", /* right */                    "M:d", /* -> */ "iu"},
	{/* left */                    "M:d", /* text */           "iv", /* right */                    "M:d", /* -> */ "iu"},
	{/* left */                    "M:*", /* text */            "i", /* right */                    "M:*", /* -> */ "i"},
	{/* left */                    "M:*", /* text */            "ī", /* right */                    "M:*", /* -> */ "ii"},
	{/* left */                    "M:v", /* text */            "j", /* right */                    "M:#", /* -> */ "i^"},
	{/* left */                    "M:v", /* text */            "j", /* right */                "U:s M:#", /* -> */ "i^"},
	{/* left */                    "U:i", /* text */            "j", /* right */                    "M:#", /* -> */ "i^"},
	{/* left */                    "M:*", /* text */            "j", /* right */                    "M:*", /* -> */ "j"},
	{/* left */                    "M:^", /* text */            "k", /* right */                    "M:b", /* -> */ "g"},
	{/* left */            "M:# M:i M:l", /* text */            "k", /* right */            "M:l U:s M:#", /* -> */ "kk"},
	{/* left */                "M:# M:l", /* text */            "k", /* right */                "M:l M:#", /* -> */ "kk"},
	{/* left */                "M:# M:l", /* text */            "k", /* right */            "M:l U:s M:#", /* -> */ "kk"},
	{/* left */            "M:# M:i M:l", /* text */            "k", /* right */                "M:l M:#", /* -> */ "kk"},
	{/* left */                    "M:*", /* text */            "k", /* right */                    "M:*", /* -> */ "k"},
	{/* left */                    "M:^", /* text */            "ķ", /* right */                    "M:b", /* -> */ "G"},
	{/* left */            "M:# M:i M:l", /* text */            "ķ", /* right */            "M:l U:s M:#", /* -> */ "KK"},
	{/* left */                "M:# M:l", /* text */            "ķ", /* right */                "M:l M:#", /* -> */ "KK"},
	{/* left */                "M:# M:l", /* text */            "ķ", /* right */            "M:l U:s M:#", /* -> */ "KK"},
	{/* left */            "M:# M:i M:l", /* text */            "ķ", /* right */                "M:l M:#", /* -> */ "KK"},
	{/* left */                    "M:*", /* text */            "ķ", /* right */                    "M:*", /* -> */ "K"},
	{/* left */                    "M:*", /* text */           "ll", /* right */                    "M:*", /* -> */ "ll"},
	{/* left */                    "M:*", /* text */            "l", /* right */                    "M:*", /* -> */ "l"},
	{/* left */                    "M:*", /* text */            "ļ", /* right */                    "M:*", /* -> */ "L"},
	{/* left */                    "M:*", /* text */           "mm", /* right */                    "M:*", /* -> */ "mm"},
	{/* left */                    "M:*", /* text */            "m", /* right */                    "M:*", /* -> */ "m"},
	{/* left */                    "M:*", /* text */           "nn", /* right */                    "M:*", /* -> */ "nn"},
	{/* left */                    "M:l", /* text */            "n", /* right */                    "U:g", /* -> */ "N"},
	{/* left */                    "M:l", /* text */            "n", /* right */                    "U:k", /* -> */ "N"},
	{/* left */                    "M:*", /* text */            "n", /* right */                    "M:*", /* -> */ "n"},
	{/* left */                    "M:*", /* text */           "ņņ", /* right */                    "M:*", /* -> */ "JJ"},
	{/* left */                    "M:*", /* text */            "ņ", /* right */                    "M:*", /* -> */ "J"},
	{/* left */                "M:* M:l", /* text */            "n", /* right */                    "U:g", /* -> */ "N"},
	{/* left */                "M:* M:l", /* text */            "n", /* right */                    "U:k", /* -> */ "N"},
	{/* left */                    "M:d", /* text */           "oj", /* right */                    "M:d", /* -> */ "oi"},
	{/* left */                    "M:^", /* text */           "oi", /* right */                    "M:#", /* -> */ "oi"},
	{/* left */                    "M:d", /* text */           "ov", /* right */                    "M:d", /* -> */ "ou"},
	{/* left */                    "M:^", /* text */           "ov", /* right */                    "M:#", /* -> */ "ou"},
	{/* left */                    "M:d", /* text */           "oo", /* right */                    "M:d", /* -> */ "oo"},
	{/* left */                    "M:d", /* text */            "o", /* right */                    "M:#", /* -> */ "uo"},
	{/* left */                    "M:d", /* text */            "o", /* right */                "U:s M:#", /* -> */ "uo"},
	{/* left */                    "M:^", /* text */            "o", /* right */    "U:t U:ā U:j M:o M:#", /* -> */ "uo"},
	{/* left */                    "M:^", /* text */            "o", /* right */    "U:š U:a U:n M:o M:#", /* -> */ "uo"},
	{/* left */                    "M:^", /* text */            "o", /* right */ "U:š U:a U:n U:ā U:s M:#", /* -> */ "uo"},
	{/* left */                    "M:^", /* text */            "o", /* right */ "U:š U:a U:n U:o U:s M:#", /* -> */ "uo"},
	{/* left */                    "M:^", /* text */            "o", /* right */            "U:ņ M:h M:#", /* -> */ "uo"},
	{/* left */                    "M:*", /* text */            "o", /* right */                "U:t M:#", /* -> */ "uo"},
	{/* left */                    "M:^", /* text */            "o", /* right */       "U:t U:ie U:s M:#", /* -> */ "uo"},
	{/* left */                    "M:^", /* text */            "o", /* right */    "U:t U:ā U:j M:h M:#", /* -> */ "uo"},
	{/* left */                    "M:^", /* text */            "o", /* right */        "U:k U:l M:r M:#", /* -> */ "uo"},
	{/* left */                    "M:^", /* text */            "o", /* right */        "U:k U:ļ M:r M:#", /* -> */ "uo"},
	{/* left */            "M:* U:s U:k", /* text */            "o", /* right */                "U:l M:^", /* -> */ "uo"},
	{/* left */                    "M:*", /* text */            "o", /* right */                "M:f M:^", /* -> */ "o"},
	{/* left */                    "M:^", /* text */            "o", /* right */            "M:* U:f M:*", /* -> */ "o"},
	{/* left */            "M:* U:f M:*", /* text */            "o", /* right */                    "M:^", /* -> */ "o"},
	{/* left */                    "M:*", /* text */            "o", /* right */        "U:l U:o M:g M:^", /* -> */ "o"},
	{/* left */                    "M:*", /* text */            "o", /* right */                "M:g M:^", /* -> */ "oo"},
	{/* left */                    "M:*", /* text */            "o", /* right */                    "M:*", /* -> */ "uo"},
	{/* left */                "M:# U:a", /* text */           "pb", /* right */                    "M:*", /* -> */ "b"},
	{/* left */                    "M:^", /* text */            "p", /* right */                    "M:b", /* -> */ "b"},
	{/* left */                    "M:^", /* text */           "pp", /* right */                    "M:^", /* -> */ "pp"},
	{/* left */            "M:# M:i M:l", /* text */            "p", /* right */            "M:l U:s M:#", /* -> */ "pp"},
	{/* left */                "M:# M:l", /* text */            "p", /* right */                "M:l M:#", /* -> */ "pp"},
	{/* left */                "M:# M:l", /* text */            "p", /* right */            "M:l U:s M:#", /* -> */ "pp"},
	{/* left */            "M:# M:i M:l", /* text */            "p", /* right */                "M:l M:#", /* -> */ "pp"},
	{/* left */                    "M:*", /* text */            "p", /* right */                    "M:*", /* -> */ "p"},
	{/* left */                    "M:*", /* text */            "r", /* right */                    "M:*", /* -> */ "r"},
	{/* left */                    "M:^", /* text */            "s", /* right */                    "M:b", /* -> */ "z"},
	{/* left */            "M:# M:i M:l", /* text */            "s", /* right */            "M:l U:s M:#", /* -> */ "ss"},
	{/* left */                "M:# M:l", /* text */            "s", /* right */                "M:l M:#", /* -> */ "ss"},
	{/* left */                "M:# M:l", /* text */            "s", /* right */            "M:l U:s M:#", /* -> */ "ss"},
	{/* left */            "M:# M:i M:l", /* text */            "s", /* right */                "M:l M:#", /* -> */ "ss"},
	{/* left */                    "M:^", /* text */           "ss", /* right */                    "M:#", /* -> */ "ss"},
	{/* left */                    "M:*", /* text */            "s", /* right */                    "M:*", /* -> */ "s"},
	{/* left */                    "M:^", /* text */           "šs", /* right */                    "M:#", /* -> */ "S"},
	{/* left */                    "M:^", /* text */            "š", /* right */                    "M:b", /* -> */ "Z"},
	{/* left */            "M:# M:i M:l", /* text */            "š", /* right */            "M:l U:s M:#", /* -> */ "SS"},
	{/* left */                "M:# M:l", /* text */            "š", /* right */                "M:l M:#", /* -> */ "SS"},
	{/* left */                "M:# M:l", /* text */            "š", /* right */            "M:l U:s M:#", /* -> */ "SS"},
	{/* left */            "M:# M:i M:l", /* text */            "š", /* right */                "M:l M:#", /* -> */ "SS"},
	{/* left */                    "M:*", /* text */            "š", /* right */                    "M:*", /* -> */ "S"},
	{/* left */                "M:# U:a", /* text */           "td", /* right */                    "M:*", /* -> */ "d"},
	{/* left */                    "M:^", /* text */           "ts", /* right */                    "M:#", /* -> */ "ts"},
	{/* left */                    "M:^", /* text */            "t", /* right */                    "M:b", /* -> */ "d"},
	{/* left */                "M:# U:a", /* text */           "tt", /* right */                    "M:^", /* -> */ "tt"},
	{/* left */            "M:# M:i M:l", /* text */            "t", /* right */            "M:l U:s M:#", /* -> */ "tt"},
	{/* left */                "M:# M:l", /* text */            "t", /* right */                "M:l M:#", /* -> */ "tt"},
	{/* left */                "M:# M:l", /* text */            "t", /* right */            "M:l U:s M:#", /* -> */ "tt"},
	{/* left */            "M:# M:i M:l", /* text */            "t", /* right */                "M:l M:#", /* -> */ "tt"},
	{/* left */                    "M:*", /* text */            "t", /* right */                    "M:*", /* -> */ "t"},
	{/* left */                    "M:*", /* text */            "u", /* right */                    "M:#", /* -> */ "ux"},
	{/* left */                    "M:d", /* text */            "u", /* right */                "U:s M:#", /* -> */ "ux"},
	{/* left */                    "M:d", /* text */           "ui", /* right */                    "M:d", /* -> */ "ui"},
	{/* left */                    "M:d", /* text */           "uj", /* right */                    "M:d", /* -> */ "ui"},
	{/* left */                    "M:^", /* text */           "uj", /* right */                    "M:#", /* -> */ "ui"},
	{/* left */                    "M:*", /* text */            "u", /* right */                    "M:*", /* -> */ "u"},
	{/* left */                    "M:*", /* text */            "ū", /* right */                    "M:*", /* -> */ "uu"},
	{/* left */                    "M:v", /* text */            "v", /* right */                    "U:s", /* -> */ "u^"},
	{/* left */                    "M:*", /* text */            "v", /* right */                    "M:*", /* -> */ "v"},
	{/* left */               "M:# U:ai", /* text */           "zs", /* right */                    "M:*", /* -> */ "ss"},
	{/* left */                "M:# U:i", /* text */           "zs", /* right */                    "M:*", /* -> */ "ss"},
	{/* left */                "M:# U:u", /* text */           "zs", /* right */                    "M:*", /* -> */ "ss"},
	{/* left */                    "M:^", /* text */           "zš", /* right */                    "M:^", /* -> */ "S"},
	{/* left */                    "M:^", /* text */           "zž", /* right */                    "M:^", /* -> */ "Z"},
	{/* left */                    "M:^", /* text */            "z", /* right */                    "M:c", /* -> */ "s"},
	{/* left */                    "U:u", /* text */           "zz", /* right */                    "M:^", /* -> */ "zz"},
	{/* left */                    "M:*", /* text */           "zs", /* right */                    "M:^", /* -> */ "ss"},
	{/* left */                    "M:*", /* text */            "z", /* right */                    "M:*", /* -> */ "z"},
	{/* left */                    "M:^", /* text */           "žs", /* right */                    "M:#", /* -> */ "S"},
	{/* left */                    "M:^", /* text */            "ž", /* right */                    "M:c", /* -> */ "S"},
	{/* left */                    "M:*", /* text */            "ž", /* right */                    "M:*", /* -> */ "Z"},
};



const std::vector<Rule>& getRules() { return rules; }
const std::map<std::string, std::vector<std::string>>& getMetaRules() { return metaRules; }

